config/routes.rb
Rails.application.routes.draw do
  # get 'carts/show'
  # get 'products/index'
  # get 'products/new'
  # get 'products/edit'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: 'products#index'
  resources :products
  resources :carts, only: [:show, :destroy]
  resources :cart_items, only: [:create, :show, :destroy, :update]

  post '/cart_items/:id/add' => 'cart_items#add_quantity', as: 'cart_item_add'
  post '/cart_items/:id/reduce' => 'cart_items#reduce_quantity', as: 'cart_item_reduce'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :products, through: :cart_items
  has_many :spend_based_discounts
  has_many :quantity_based_discounts

  def total_without_discount
    sum = 0
    cart_items.each do |cart_item|
      sum += cart_item.quantity * Product.where(id: cart_item.product.id).first.price
    end
    sum
  end

  def sub_total
    sum = 0
    quantity_based_discounts = QuantityBasedDiscount.all

    cart_items.each do |cart_item|
      is_quantity_based_discount = false
      quantity_based_discounts.each do |discount|
        if ((discount.min_quantity <= cart_item.quantity) && (discount.product_id == cart_item.product.id))
          sum += discount.new_price * cart_item.quantity
          is_quantity_based_discount = true
        end
      end
      unless is_quantity_based_discount
        sum += cart_item.total_price
      end
    end
    spend_based_discount = SpendBasedDiscount.all
    spend_based_discount.each do |discount|
      if discount.min_spending < sum
        sum -= sum * discount.discount / 100
      end
    end
    sum
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart

  def total_price
    quantity_based_discounts = QuantityBasedDiscount.all
    quantity_based_discounts.each do |discount|
      if ((discount.min_quantity <= self.quantity) && (discount.product_id == self.product.id))
        return discount.new_price * self.quantity
      end
    end
    self.quantity * self.product.price
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :cart_items, dependent: :destroy
end

app/models/quantity_based_discount.rb
class QuantityBasedDiscount < ApplicationRecord
  belongs_to :product
end

app/models/spend_based_discount.rb
class SpendBasedDiscount < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :current_cart

  private

  def current_cart
    if session[:cart_id]
      cart = Cart.find_by(:id => session[:cart_id])
      if cart.present?
        @current_cart = cart
      else
        session[:cart_id] = nil
      end
    end

    if session[:cart_id] == nil
      @current_cart = Cart.create
      session[:cart_id] = @current_cart.id
    end
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController

  def index
    @cart_items = CartItems.all
  end

  def show
    @cart_item = CartItem.find(params[:id])
  end

  def create
    # Find associated product and current cart
    chosen_product = Product.find(params[:product_id])
    current_cart = @current_cart

    # If cart already has this product then find the relevant cart_item and iterate quantity otherwise create a new cart_item for this product
    if current_cart.products.include?(chosen_product)
      # Find the cart_item with the chosen_product
      @cart_item = current_cart.cart_items.find_by(:product_id => chosen_product)
      # Iterate the cart_item's quantity by one
      @cart_item.quantity += 1
    else
      @cart_item = CartItem.new
      @cart_item.cart = current_cart
      @cart_item.product = chosen_product
      @cart_item.quantity = 1
    end

    # Save and redirect to cart show path
    @cart_item.save
    redirect_to cart_path(current_cart)
  end

  def destroy
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
    redirect_to cart_path(@current_cart)
  end

  def add_quantity
    @cart_item = CartItem.find(params[:id])
    @cart_item.quantity += 1
    @cart_item.save
    redirect_to cart_path(@current_cart)
  end

  def reduce_quantity
    @cart_item = CartItem.find(params[:id])
    if @cart_item.quantity > 1
      @cart_item.quantity -= 1
    else
      @cart_item.destroy
    end
    @cart_item.save
    redirect_to cart_path(@current_cart)
  end

  private

  def cart_item_params
    params.require(:cart_item).permit(:quantity, :product_id, :cart_id)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart = @current_cart
  end

  def destroy
    @cart = @current_cart
    @cart.destroy
    session[:cart_id] = nil
    redirect_to root_path
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.create(product_params)
    redirect_to products_path
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product.update(product_params)
    redirect_to products_path
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  private

  def product_params
    params.require(:product).permit(:product_code, :name, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/show.html.erb
<div class="container">
  <center><h1>Cart Show</h1></center>
  <div class="container mt-5">
    <% @cart.cart_items.each do |cart_item| %>
      <h5><strong>Item: </strong><%= cart_item.product.name %></h5>
      <h5><strong>Price: </strong><%= number_to_currency(cart_item.product.price) %></h5>
      <h5><strong>Quantity: </strong><%= cart_item.quantity %></h5>
      <h5><strong>Total Price: </strong><%= number_to_currency(cart_item.total_price) %></h5>
      <%= link_to "Add More", cart_item_add_path(cart_item), data: {turbo_method: :post}, class: "btn btn-primary", style:"background-color:blue" %>
      <%= link_to "Reduce", cart_item_reduce_path(cart_item), data: {turbo_method: :post}, class: "btn btn-primary", style:"background-color:red" %>
      <br>
      <br>
    <% end %>
  </div>
  <hr>
  <div class="container mt-4">
    <h4>Discount: <%= number_to_currency(@cart.total_without_discount - @cart.sub_total) %></h4>
    <h4>Total: <%= number_to_currency(@cart.sub_total) %></h4>
    <%= link_to "Add more items", products_path, class: "btn btn-primary", style:"background-color:blue" %>
    <%= link_to "Empty Cart", cart_path(@current_cart), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-primary", style:"background-color:red" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OnlineMarketplace</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/edit.html.erb
<%= form_for(@product) do |f| %>
  <p>
    <%= f.label :product_code %><br>
    <%= f.text_field :product_code, required: true, autofocus: true, placeholder: "Enter product code" %>
  </p>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name, required: true, autofocus: true, placeholder: "Enter product name" %>
  </p>
  <p>
    <%= f.label :price %><br>
    <%= f.text_field :price, required: true %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/products/index.html.erb
  <center><h1>All Products</h1></center>
<div class="container mt-5 d-flex justify-content-between">
  <div class="container">
    <% @products.each do |product| %>
      <h5>Name: <%= product.name %></h5>
      <h5>Unit Price: <%= number_to_currency(product.price) %></h5>
      <p>
        <%= link_to "Edit", edit_product_path(product), class: "btn btn-primary", style:"background-color:blue" %>
        <%= link_to "Delete", product_path(product), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-primary", style:"background-color:red" %>
        <%= button_to "Add to cart", cart_items_path(:product_id => product.id) %>
      </p>
      <hr>
    <% end%>
    <br>
    <%= link_to "Add New Product", new_product_path, class: "btn btn-primary", style:"background-color:blue" %>
  </div>
  <div class="container mt-5">
    <%= link_to "Go to Cart", cart_path(@current_cart), class: "btn btn-primary", style:"background-color:blue" %>
  </div>
</div>

app/views/products/new.html.erb
<%= form_for(@product) do |f| %>
  <p>
    <%= f.label :product_code %><br>
    <%= f.text_field :product_code, required: true, autofocus: true, placeholder: "Enter product code" %>
  </p>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name, required: true, autofocus: true, placeholder: "Enter product name" %>
  </p>
  <p>
    <%= f.label :price %><br>
    <%= f.text_field :price, required: true %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>